import { ResearchResult } from '@/types/llm.types';
import { ExternalLink } from 'lucide-react';
import { FounderProfileView } from './founder-profile-view';

interface ResearchSummaryProps {
  result: ResearchResult;
}

export function ResearchSummary({ result }: ResearchSummaryProps) {
  return (
    <div className="p-4 space-y-6 max-w-4xl">
      <section>
        <h3 className="text-accent font-medium text-text-primary mb-3">
          Executive Summary
        </h3>
        <div className="text-sm leading-relaxed whitespace-pre-wrap">
          {result.domain === 'founder_profile' ? result.executiveSummary : result.summary}
        </div>
      </section>

      <section>
        <h3 className="text-base font-medium text-text-primary mb-2">
          Sources
        </h3>
        <div className="flex flex-wrap gap-1.5">
          {result.sources.map((url, i) => (
            <a
              key={i}
              href={url}
              target="_blank"
              rel="noopener noreferrer"
              title={url}
              className="inline-flex items-center gap-1 px-2 py-0.5 bg-tertiary hover:bg-quaternary text-text-tertiary hover:text-accent text-xs rounded transition-colors border border-border"
            >
              <ExternalLink className="w-3 h-3" />
              <span>{url.replace(/^(https?:\/\/)?(www\.)?/, '').split(/[/?#]/)[0] || url}</span>
            </a>
          ))}
        </div>
      </section>

      {result.domain === 'founder_profile' && (
        <FounderProfileView result={result} />
      )}

      {result.domain === 'traction' && (
        <section>
          <h3 className="text-accent font-medium text-text-primary mb-3">
            Traction Signals
          </h3>
          <ul className="space-y-2 text-sm">
            {result.tractionSignals.map((signal, i) => (
              <li key={i} className="flex gap-2">
                <span className="text-accent flex-shrink-0">•</span>
                <span className="text-text-primary">{signal}</span>
              </li>
            ))}
          </ul>
        </section>
      )}

      {result.metadata?.isAutoGenerated === true && (
        <div className="mt-6 pt-4 border-t border-border">
          <p className="text-xs text-text-tertiary italic">
            This summary was automatically generated from the research timeline.
          </p>
        </div>
      )}
    </div>
  );
}
