import { ResearchResult } from '@/types/llm.types';
import { ExternalLink } from 'lucide-react';

interface ResearchSummaryProps {
  result: ResearchResult;
}

export function ResearchSummary({ result }: ResearchSummaryProps) {
  return (
    <div className="p-6 space-y-6 max-w-4xl">
      <section>
        <h3 className="text-accent font-medium text-text-primary mb-3">
          Executive Summary
        </h3>
        <div className="text-sm leading-relaxed whitespace-pre-wrap">
          {result.summary}
        </div>
      </section>

      {result.keyFindings && result.keyFindings.length > 0 && (
        <section>
          <h3 className="text-accent font-medium text-text-primary mb-3">
            Key Findings
          </h3>
          <ul className="space-y-2 text-sm">
            {result.keyFindings.map((finding, i) => (
              <li key={i} className="flex gap-2">
                <span className="text-accent flex-shrink-0">•</span>
                <span>{finding}</span>
              </li>
            ))}
          </ul>
        </section>
      )}

      <section>
        <h3 className="text-base font-medium text-text-primary mb-3">
          Sources
        </h3>
        <ul className="space-y-1.5 text-sm">
          {result.sources.map((url, i) => (
            <li key={i}>
              <a
                href={url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-accent hover:text-accent-hover transition-colors inline-flex items-center gap-1.5 group"
              >
                <ExternalLink className="w-3.5 h-3.5 flex-shrink-0 opacity-60 group-hover:opacity-100 transition-opacity" aria-hidden="true" />
                <span className="break-all">{url}</span>
              </a>
            </li>
          ))}
        </ul>
      </section>

      {result.metadata?.isAutoGenerated === true && (
        <div className="mt-6 pt-4 border-t border-border">
          <p className="text-xs text-text-tertiary italic">
            This summary was automatically generated from the research timeline.
          </p>
        </div>
      )}
    </div>
  );
}
