/**
 * Manual alias maps for query filter extraction.
 * Keys are normalized (lowercase, trimmed) user-typed tokens.
 * Values are canonical stored values.
 */

/** Maps short-form YC batch notation to stored full-form batch names. */
export const BATCH_ALIASES: Record<string, string> = {
  // Winter batches
  'w05': 'Winter 2005', 'w06': 'Winter 2006', 'w07': 'Winter 2007',
  'w08': 'Winter 2008', 'w09': 'Winter 2009', 'w10': 'Winter 2010',
  'w11': 'Winter 2011', 'w12': 'Winter 2012', 'w13': 'Winter 2013',
  'w14': 'Winter 2014', 'w15': 'Winter 2015', 'w16': 'Winter 2016',
  'w17': 'Winter 2017', 'w18': 'Winter 2018', 'w19': 'Winter 2019',
  'w20': 'Winter 2020', 'w21': 'Winter 2021', 'w22': 'Winter 2022',
  'w23': 'Winter 2023', 'w24': 'Winter 2024', 'w25': 'Winter 2025',
  'w26': 'Winter 2026',
  'w2005': 'Winter 2005', 'w2006': 'Winter 2006', 'w2007': 'Winter 2007',
  'w2008': 'Winter 2008', 'w2009': 'Winter 2009', 'w2010': 'Winter 2010',
  'w2011': 'Winter 2011', 'w2012': 'Winter 2012', 'w2013': 'Winter 2013',
  'w2014': 'Winter 2014', 'w2015': 'Winter 2015', 'w2016': 'Winter 2016',
  'w2017': 'Winter 2017', 'w2018': 'Winter 2018', 'w2019': 'Winter 2019',
  'w2020': 'Winter 2020', 'w2021': 'Winter 2021', 'w2022': 'Winter 2022',
  'w2023': 'Winter 2023', 'w2024': 'Winter 2024', 'w2025': 'Winter 2025',
  'w2026': 'Winter 2026',
  // Summer batches
  's05': 'Summer 2005', 's06': 'Summer 2006', 's07': 'Summer 2007',
  's08': 'Summer 2008', 's09': 'Summer 2009', 's10': 'Summer 2010',
  's11': 'Summer 2011', 's12': 'Summer 2012', 's13': 'Summer 2013',
  's14': 'Summer 2014', 's15': 'Summer 2015', 's16': 'Summer 2016',
  's17': 'Summer 2017', 's18': 'Summer 2018', 's19': 'Summer 2019',
  's20': 'Summer 2020', 's21': 'Summer 2021', 's22': 'Summer 2022',
  's23': 'Summer 2023', 's24': 'Summer 2024', 's25': 'Summer 2025',
  's2005': 'Summer 2005', 's2006': 'Summer 2006', 's2007': 'Summer 2007',
  's2008': 'Summer 2008', 's2009': 'Summer 2009', 's2010': 'Summer 2010',
  's2011': 'Summer 2011', 's2012': 'Summer 2012', 's2013': 'Summer 2013',
  's2014': 'Summer 2014', 's2015': 'Summer 2015', 's2016': 'Summer 2016',
  's2017': 'Summer 2017', 's2018': 'Summer 2018', 's2019': 'Summer 2019',
  's2020': 'Summer 2020', 's2021': 'Summer 2021', 's2022': 'Summer 2022',
  's2023': 'Summer 2023', 's2024': 'Summer 2024', 's2025': 'Summer 2025',
  // Fall batches
  'f24': 'Fall 2024', 'f25': 'Fall 2025',
  'f2024': 'Fall 2024', 'f2025': 'Fall 2025',
  'fall24': 'Fall 2024', 'fall25': 'Fall 2025',
  // Spring batches
  'x25': 'Spring 2025', 'x26': 'Spring 2026',
  'x2025': 'Spring 2025', 'x2026': 'Spring 2026',
  'sp25': 'Spring 2025', 'sp26': 'Spring 2026',
  'sp2025': 'Spring 2025', 'sp2026': 'Spring 2026',
  'spring25': 'Spring 2025', 'spring26': 'Spring 2026',
};

/** Stage keyword aliases → stored stage values. */
export const STAGE_ALIASES: Record<string, string> = {
  'early stage': 'Early',
  'early-stage': 'Early',
  'seed stage': 'Early',
  'seed': 'Early',
  'pre-seed': 'Early',
  'preseed': 'Early',
  'series a': 'Early',
  'series-a': 'Early',
  'growth stage': 'Growth',
  'growth-stage': 'Growth',
  'late stage': 'Growth',
  'late-stage': 'Growth',
  'series b': 'Growth',
  'series-b': 'Growth',
  'series c': 'Growth',
  'series-c': 'Growth',
  'series d': 'Growth',
  'series-d': 'Growth',
};

/** Status keyword aliases → stored status values. */
export const STATUS_ALIASES: Record<string, string> = {
  'acquired': 'Acquired',
  'acquisition': 'Acquired',
  'was acquired': 'Acquired',
  'ipo': 'Public',
  'went public': 'Public',
  'publicly traded': 'Public',
  'went ipo': 'Public',
  'inactive': 'Inactive',
  'dead': 'Inactive',
  'defunct': 'Inactive',
  'shut down': 'Inactive',
  'failed': 'Inactive',
  'closed': 'Inactive',
};

/** Tag/industry aliases → stored tag/industry values (can map to multiple). */
export const TAG_ALIASES: Record<string, string[]> = {
  'ai': ['AI', 'Artificial Intelligence'],
  'artificial intelligence': ['Artificial Intelligence', 'AI'],
  'ml': ['Machine Learning', 'ML'],
  'machine learning': ['Machine Learning'],
  'generative ai': ['Generative AI'],
  'genai': ['Generative AI'],
  'gen ai': ['Generative AI'],
  'llm': ['Artificial Intelligence', 'Generative AI'],
  'large language model': ['Artificial Intelligence', 'Generative AI'],
  'saas': ['SaaS'],
  'b2b': ['B2B'],
  'b2c': ['Consumer'],
  'developer tools': ['Developer Tools'],
  'devtools': ['Developer Tools'],
  'dev tools': ['Developer Tools'],
  'web3': ['Crypto / Web3'],
  'crypto': ['Crypto / Web3'],
  'cryptocurrency': ['Crypto / Web3'],
  'blockchain': ['Blockchain', 'Crypto / Web3'],
  'defi': ['DeFi', 'Crypto / Web3'],
  'nft': ['NFT'],
  'no code': ['No-code'],
  'nocode': ['No-code'],
  'no-code': ['No-code'],
  'low code': ['No-code'],
  'lowcode': ['No-code'],
  'low-code': ['No-code'],
  'fintech': ['Fintech'],
  'healthtech': ['Health Tech'],
  'health tech': ['Health Tech'],
  'edtech': ['Edtech', 'Education'],
  'ed tech': ['Edtech', 'Education'],
  'proptech': ['Proptech', 'Real Estate'],
  'prop tech': ['Proptech', 'Real Estate'],
  'govtech': ['GovTech'],
  'gov tech': ['GovTech'],
  'legaltech': ['LegalTech'],
  'legal tech': ['LegalTech'],
  'regtech': ['Regtech'],
  'insurtech': ['Insurance'],
  'biotech': ['Biotech'],
  'deep tech': ['Hard Tech'],
  'deeptech': ['Hard Tech'],
  'hard tech': ['Hard Tech'],
  'hardtech': ['Hard Tech'],
  'autonomous': ['Robotics', 'Automation'],
  'cybersecurity': ['Cybersecurity', 'Security'],
  'cyber security': ['Cybersecurity', 'Security'],
  'devops': ['DevOps'],
  'devsecops': ['DevSecOps'],
  'open source': ['Open Source'],
  'opensource': ['Open Source'],
  'nlp': ['NLP'],
  'natural language processing': ['NLP'],
  'computer vision': ['Computer Vision'],
  'cv': ['Computer Vision'],
  'iot': ['IoT'],
  'internet of things': ['IoT'],
  'ar': ['Augmented Reality', 'AR'],
  'vr': ['Virtual Reality'],
  'augmented reality': ['Augmented Reality'],
  'virtual reality': ['Virtual Reality'],
  'xr': ['Virtual Reality', 'Augmented Reality'],
  'ecommerce': ['E-commerce', 'E-Commerce'],
  'e-commerce': ['E-commerce', 'E-Commerce'],
  'marketplace': ['Marketplace'],
  'analytics': ['Analytics'],
  'data analytics': ['Analytics', 'Data Science'],
  'infrastructure': ['Infrastructure'],
  'cloud': ['Cloud Computing'],
  'cloud computing': ['Cloud Computing'],
  'api': ['API'],
  'apis': ['API'],
  'enterprise': ['Enterprise', 'Enterprise Software'],
  'enterprise software': ['Enterprise Software'],
  'smb': ['SMB'],
  'small business': ['SMB'],
  'climate': ['Climate', 'ClimateTech'],
  'climatetech': ['ClimateTech', 'Climate'],
  'climate tech': ['ClimateTech', 'Climate'],
  'cleantech': ['Climate', 'Energy'],
  'clean tech': ['Climate', 'Energy'],
  'renewable energy': ['Renewable Energy', 'Energy'],
  'solar': ['Solar Power', 'Energy'],
  'electric vehicle': ['Electric Vehicles'],
  'ev': ['Electric Vehicles'],
  'healthcare': ['Healthcare'],
  'health care': ['Healthcare'],
  'digital health': ['Digital Health'],
  'telehealth': ['Telehealth', 'Telemedicine'],
  'telemedicine': ['Telemedicine', 'Telehealth'],
  'mental health': ['Mental Health Tech', 'Mental Health'],
  'hr tech': ['HR Tech'],
  'hrtech': ['HR Tech'],
  'human resources': ['Human Resources', 'HR Tech'],
  'recruiting': ['Recruiting', 'Recruiting and Talent'],
  'talent': ['Recruiting', 'Recruiting and Talent'],
  'sales': ['Sales'],
  'sales enablement': ['Sales Enablement'],
  'marketing': ['Marketing'],
  'adtech': ['Advertising'],
  'ad tech': ['Advertising'],
  'gaming': ['Gaming'],
  'game': ['Gaming'],
  'social': ['Social', 'Social Network'],
  'social media': ['Social Media', 'Social'],
  'creator': ['Creator Economy'],
  'creator economy': ['Creator Economy'],
  'media': ['Media'],
  'content': ['Content'],
  'video': ['Video'],
  'audio': ['Media'],
  'podcast': ['Podcasts'],
  'logistics': ['Logistics', 'Supply Chain'],
  'supply chain': ['Supply Chain'],
  'manufacturing': ['Manufacturing'],
  'robotics': ['Robotics', 'Manufacturing and Robotics'],
  'space': ['Space Exploration', 'Aerospace'],
  'aerospace': ['Aerospace'],
  'defense': ['Defense'],
  'agriculture': ['Agriculture'],
  'agtech': ['Agriculture'],
  'ag tech': ['Agriculture'],
  'food tech': ['Food Tech'],
  'foodtech': ['Food Tech'],
  'food': ['Food Tech', 'Food & Beverage'],
  'grocery': ['Grocery'],
  'retail': ['Retail'],
  'fashion': ['Fashion'],
  'real estate': ['Real Estate', 'Proptech'],
  'construction': ['Construction'],
  'automotive': ['Automotive'],
  'transportation': ['Transportation'],
  'travel': ['Travel'],
  'payments': ['Payments'],
  'finops': ['FinOps'],
  'compliance': ['Compliance'],
  'legal': ['Legal', 'LegalTech'],
  'insurance': ['Insurance'],
  'neobank': ['Neobank'],
  'banking': ['Banking as a Service'],
  'productivity': ['Productivity'],
  'collaboration': ['Collaboration'],
  'workflow': ['Workflow Automation', 'Automation'],
  'automation': ['Automation', 'Workflow Automation'],
  'rpa': ['Robotic Process Automation'],
  'nonprofit': ['Nonprofit'],
  'non-profit': ['Nonprofit'],
  'education': ['Education'],
  'learning': ['AI-Enhanced Learning', 'eLearning', 'Education'],
  'elearning': ['eLearning'],
  'e-learning': ['eLearning'],
  'data science': ['Data Science'],
  'data engineering': ['Data Engineering'],
  'big data': ['Big Data'],
  'databases': ['Databases'],
  'security': ['Security', 'Cybersecurity'],
  'privacy': ['Privacy'],
  'identity': ['Identity'],
  'fraud': ['Fraud Detection', 'Fraud Prevention'],
  'lending': ['Lending', 'Credit and Lending'],
  'credit': ['Credit and Lending'],
  'investing': ['Investing'],
  'asset management': ['Asset Management'],
  'wealth management': ['Asset Management', 'Investing'],
  'genomics': ['Genomics'],
  'drug discovery': ['AI-powered Drug Discovery', 'Drug discovery'],
  'therapeutics': ['Therapeutics'],
  'diagnostics': ['Diagnostics'],
  'semiconductors': ['Semiconductors'],
  'hardware': ['Hardware'],
  'drones': ['Drones'],
  'satellite': ['Satellites'],
  'quantum': ['Quantum Computing'],
};

/** Region aliases → stored region values. */
export const REGION_ALIASES: Record<string, string[]> = {
  'us': ['United States of America', 'America / Canada'],
  'usa': ['United States of America', 'America / Canada'],
  'united states': ['United States of America', 'America / Canada'],
  'america': ['America / Canada', 'United States of America'],
  'north america': ['America / Canada'],
  'uk': ['United Kingdom', 'Europe'],
  'britain': ['United Kingdom', 'Europe'],
  'great britain': ['United Kingdom', 'Europe'],
  'england': ['United Kingdom', 'Europe'],
  'remote': ['Remote', 'Fully Remote', 'Partly Remote'],
  'fully remote': ['Fully Remote'],
  'fully-remote': ['Fully Remote'],
  'remote first': ['Fully Remote', 'Remote'],
  'remote-first': ['Fully Remote', 'Remote'],
  'distributed': ['Fully Remote', 'Remote'],
  'partly remote': ['Partly Remote'],
  'hybrid': ['Partly Remote'],
  'latam': ['Latin America'],
  'latin america': ['Latin America'],
  'mena': ['Middle East and North Africa'],
  'middle east': ['Middle East and North Africa'],
  'sea': ['Southeast Asia'],
  'southeast asia': ['Southeast Asia'],
  'south asia': ['South Asia'],
  'east asia': ['East Asia'],
  'asia': ['Southeast Asia', 'South Asia', 'East Asia'],
  'apac': ['Southeast Asia', 'East Asia', 'Oceania'],
  'europe': ['Europe'],
  'africa': ['Africa'],
  'india': ['India', 'South Asia'],
  'canada': ['Canada', 'America / Canada'],
  'france': ['France', 'Europe'],
  'germany': ['Germany', 'Europe'],
  'singapore': ['Singapore', 'Southeast Asia'],
  'brazil': ['Brazil', 'Latin America'],
  'mexico': ['Mexico', 'Latin America'],
  'nigeria': ['Nigeria', 'Africa'],
  'israel': ['Israel', 'Middle East and North Africa'],
  'colombia': ['Colombia', 'Latin America'],
  'indonesia': ['Indonesia', 'Southeast Asia'],
  'chile': ['Chile', 'Latin America'],
  'argentina': ['Argentina', 'Latin America'],
  'spain': ['Spain', 'Europe'],
  'australia': ['Australia', 'Oceania'],
  'netherlands': ['Netherlands', 'Europe'],
  'switzerland': ['Switzerland', 'Europe'],
  'uae': ['United Arab Emirates', 'Middle East and North Africa'],
  'dubai': ['United Arab Emirates', 'Middle East and North Africa'],
  'kenya': ['Kenya', 'Africa'],
  'sweden': ['Sweden', 'Europe'],
  'pakistan': ['Pakistan', 'South Asia'],
  'philippines': ['Philippines', 'Southeast Asia'],
  'china': ['China', 'East Asia'],
  'vietnam': ['Vietnam', 'Southeast Asia'],
  'south korea': ['South Korea', 'East Asia'],
  'korea': ['South Korea', 'East Asia'],
  'japan': ['Japan', 'East Asia'],
  'turkey': ['Turkey'],
  'ireland': ['Ireland', 'Europe'],
  'hong kong': ['Hong Kong', 'East Asia'],
  'malaysia': ['Malaysia', 'Southeast Asia'],
  'ghana': ['Ghana', 'Africa'],
  'egypt': ['Egypt', 'Middle East and North Africa'],
  'denmark': ['Denmark', 'Europe'],
  'norway': ['Norway', 'Europe'],
  'austria': ['Austria', 'Europe'],
  'saudi arabia': ['Saudi Arabia', 'Middle East and North Africa'],
  'poland': ['Poland', 'Europe'],
  'portugal': ['Portugal', 'Europe'],
  'belgium': ['Belgium', 'Europe'],
  'finland': ['Finland', 'Europe'],
  'italy': ['Italy', 'Europe'],
  'estonia': ['Estonia', 'Europe'],
  'south africa': ['South Africa', 'Africa'],
};

/** Location city aliases for the ILIKE location filter. */
export const LOCATION_ALIASES: Record<string, string> = {
  'sf': 'San Francisco',
  'san francisco': 'San Francisco',
  'bay area': 'San Francisco',
  'silicon valley': 'San Francisco',
  'sv': 'San Francisco',
  'nyc': 'New York',
  'new york': 'New York',
  'new york city': 'New York',
  'ny': 'New York',
  'la': 'Los Angeles',
  'los angeles': 'Los Angeles',
  'london': 'London',
  'boston': 'Boston',
  'seattle': 'Seattle',
  'austin': 'Austin',
  'chicago': 'Chicago',
  'denver': 'Denver',
  'toronto': 'Toronto',
  'berlin': 'Berlin',
  'paris': 'Paris',
  'tel aviv': 'Tel Aviv',
  'bangalore': 'Bengaluru',
  'bengaluru': 'Bengaluru',
  'mumbai': 'Mumbai',
  'delhi': 'Delhi',
  'new delhi': 'Delhi',
  'palo alto': 'Palo Alto',
  'mountain view': 'Mountain View',
  'san jose': 'San Jose',
  'atlanta': 'Atlanta',
  'miami': 'Miami',
  'philadelphia': 'Philadelphia',
  'washington dc': 'Washington',
  'dc': 'Washington',
  'vancouver': 'Vancouver',
  'montreal': 'Montreal',
  'amsterdam': 'Amsterdam',
  'stockholm': 'Stockholm',
  'zurich': 'Zurich',
  'dubai': 'Dubai',
  'sydney': 'Sydney',
  'melbourne': 'Melbourne',
  'tokyo': 'Tokyo',
  'beijing': 'Beijing',
  'shanghai': 'Shanghai',
  'seoul': 'Seoul',
  'jakarta': 'Jakarta',
  'mexico city': 'Mexico City',
  'sao paulo': 'São Paulo',
  'lagos': 'Lagos',
  'nairobi': 'Nairobi',
  'cairo': 'Cairo',
};

/** Phrases that signal is_hiring = true. */
export const HIRING_PHRASES = new Set([
  'hiring', 'is hiring', 'actively hiring', 'currently hiring',
  'open roles', 'open positions', 'open to hiring', 'looking to hire',
  'recruiting', 'has openings', 'has jobs',
]);

/** Phrases that signal is_nonprofit = true. */
export const NONPROFIT_PHRASES = new Set([
  'nonprofit', 'non-profit', 'non profit', 'ngo',
  '501c3', '501(c)(3)', 'charity', 'charitable', 'not for profit',
  'not-for-profit',
]);

/** Words to strip from the query after extraction (add no semantic value). */
export const STOPWORDS = new Set([
  // Entity nouns
  'companies', 'company', 'startup', 'startups', 'firm', 'firms',
  'business', 'businesses', 'venture', 'ventures',
  // Function words
  'that', 'with', 'and', 'or', 'in', 'the', 'a', 'an', 'of',
  'for', 'on', 'at', 'to', 'by', 'from', 'about', 'which', 'who',
  'its', 'are', 'is', 'have', 'has', 'been', 'be',
  // Common query modifiers with no company-description value
  'founded', 'based', 'global', 'worldwide', 'international',
  'world', 'region', 'regions', 'everywhere', 'all', 'any',
  'top', 'best', 'good', 'great', 'popular', 'leading', 'notable',
  'new', 'latest', 'recent', 'modern', 'today',
  'some', 'many', 'most', 'other', 'similar',
]);
